"""Shared parameters for the custom California king storage bed."""

# Sleep-system and exterior geometry. Delivered measurements remain authoritative.
MATTRESS_LENGTH = 84.0
MATTRESS_WIDTH = 72.0
MATTRESS_HEIGHT = 11.0
MATTRESS_SIDE_MARGIN = 2.0
MATTRESS_FOOT_MARGIN = 2.0
DECK_HEIGHT = 3.0
FLOOR_CLEARANCE = 5.0
PEDESTAL_HEIGHT = 8.0
HEADBOARD_HEIGHT = 36.0
HEADBOARD_DEPTH = 14.0
HEADBOARD_TOP_DEPTH = 7.0
MATTRESS_OVERLAP = 4.0
OVERALL_LENGTH = HEADBOARD_DEPTH + MATTRESS_LENGTH - MATTRESS_OVERLAP + MATTRESS_FOOT_MARGIN
FRAME_WIDTH = MATTRESS_WIDTH + 2 * MATTRESS_SIDE_MARGIN
SLEEP_SYSTEM_X = HEADBOARD_DEPTH - MATTRESS_OVERLAP

# Construction and pod geometry.
PLYWOOD_THICKNESS = 0.75
STRUCTURAL_PLYWOOD_THICKNESS = 23 / 32
FINISH_PLYWOOD_THICKNESS = PLYWOOD_THICKNESS
FOOT_FASCIA_THICKNESS = 0.25
HEADBOARD_PANEL_THICKNESS = PLYWOOD_THICKNESS
FACE_THICKNESS = PLYWOOD_THICKNESS
DRAWER_FACE_HEIGHT = 6.0
SUPPORT_WIDTH = 3.0
SUPPORT_EDGE_INSET = 2.5
POD_SLIDE_LENGTH = 16.0
POD_END_CAP_THICKNESS = PLYWOOD_THICKNESS
POD_WALL_THICKNESS = PLYWOOD_THICKNESS
POD_CLEARANCE = 0.0625
POD_BODY_WIDTH = POD_SLIDE_LENGTH + POD_END_CAP_THICKNESS + POD_WALL_THICKNESS + 2 * POD_CLEARANCE
POD_EXTENSION = 16.0
POD_SHELF_THICKNESS = PLYWOOD_THICKNESS
POD_RAIL_HEIGHT = 3.0
POD_WALL_TOP = 26.0
POD_SLIDE_THICKNESS = 0.75
POD_MODULE_FLOOR_THICKNESS = PLYWOOD_THICKNESS
WALL_CLEAT_DEPTH = PLYWOOD_THICKNESS
WALL_CLEAT_HEIGHT = 3.0

# Structural module geometry.
STRUCTURAL_LENGTH = OVERALL_LENGTH - FOOT_FASCIA_THICKNESS
STRUCTURAL_FRAME_WIDTH = FRAME_WIDTH - 2 * FACE_THICKNESS
MODULE_LENGTH = STRUCTURAL_LENGTH / 2
CENTER_MODULE_WIDTH = 20.0
SIDE_MODULE_WIDTH = (STRUCTURAL_FRAME_WIDTH - CENTER_MODULE_WIDTH) / 2
CROSSMEMBER_WIDTH = 2 * STRUCTURAL_PLYWOOD_THICKNESS
CROSSMEMBER_NOTCH_CLEARANCE = 1 / 32
CROSSMEMBER_DEPTH = 5.5
CROSSMEMBER_X_RANGES = (
    (0.0, CROSSMEMBER_WIDTH),
    (MODULE_LENGTH / 2 - CROSSMEMBER_WIDTH / 2, MODULE_LENGTH / 2 + CROSSMEMBER_WIDTH / 2),
    (MODULE_LENGTH - CROSSMEMBER_WIDTH / 2, MODULE_LENGTH + CROSSMEMBER_WIDTH / 2),
    (MODULE_LENGTH + MODULE_LENGTH / 2 - CROSSMEMBER_WIDTH / 2, MODULE_LENGTH + MODULE_LENGTH / 2 + CROSSMEMBER_WIDTH / 2),
    (STRUCTURAL_LENGTH - CROSSMEMBER_WIDTH, STRUCTURAL_LENGTH),
)
SERVICE_OPENING_WIDTH = 12.0
STRUCTURAL_SUPPORT_SIZE = 3.5
SUPPORT_PAD_THICKNESS = 1 / 16
SUPPORT_CAPTURE_CLEARANCE = 1 / 16
SUPPORT_CAPTURE_CLEAT_WIDTH = 0.75
SUPPORT_CAPTURE_CLEAT_HEIGHT = 0.75
ADAPTER_PANEL_THICKNESS = 0.25
ADAPTER_SUPPORT_RAIL_WIDTH = 3.0
ADAPTER_SUPPORT_RAIL_HEIGHT = 1.5
DRAWER_SLIDE_LENGTH = 24.0
DRAWER_SLIDE_SIDE_CLEARANCE = 0.5
DRAWER_SLIDE_CARRIER_HEIGHT = 4.0
SEAM_BOLT_DIAMETER = 0.375
SEAM_BOLT_CLEARANCE_DIAMETER = 0.4375
SEAM_BOLT_WASHER_OD = 1.25
SEAM_SOCKET_ENVELOPE_DIAMETER = 1.0
SEAM_BOLT_SCREENING_BEARING_STRESS = 625.0
# Provisional lateral screen equal to 12.5% of the distributed vertical load.
LATERAL_RACKING_SCREEN_LOAD = 250.0

# Working structural-screening loads and properties, not a final engineering rating.
CHASSIS_DISTRIBUTED_DESIGN_LOAD = 2000.0
CHASSIS_EDGE_POINT_LOAD = 500.0
PLYWOOD_SCREENING_MODULUS = 1_000_000.0
PLYWOOD_SCREENING_BENDING_ALLOWABLE = 1_000.0
PLYWOOD_SCREENING_COMPRESSION_ALLOWABLE = 300.0
DEFLECTION_LIMIT_RATIO = 360.0

OCCUPANT_DESIGN_LOAD = 750.0
POWER_FLEX_ADVERTISED_CAPACITY = 850.0
